//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangKyDichVu
    {
        public string MaDangKyDV { get; set; }
        public string MaDichVu { get; set; }
        public string MaPhong { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> DonGia { get; set; }
    
        public virtual QuanLyDichVu QuanLyDichVu { get; set; }
        public virtual Phong Phong { get; set; }
    }
}
