//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public string MaHoaDon { get; set; }
        public string TenKhachHang { get; set; }
        public string CMND { get; set; }
        public string SoDienThoai { get; set; }
        public string MaPhong { get; set; }
        public Nullable<System.DateTime> NgayThue { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public Nullable<double> TongTienDichVu { get; set; }
        public Nullable<double> TongTienThanhToan { get; set; }
    
        public virtual Phong Phong { get; set; }
    }
}
