//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThuePhong
    {
        public string MaThuePhong { get; set; }
        public string MaKhachHang { get; set; }
        public Nullable<System.DateTime> NgayThue { get; set; }
        public string MaPhong { get; set; }
    
        public virtual Phong Phong { get; set; }
        public virtual ThongTinKhachHang ThongTinKhachHang { get; set; }
    }
}
