//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class VatTu
    {
        public string MaVatTu { get; set; }
        public string TenVatTu { get; set; }
        public string NhaCungCap { get; set; }
        public string NguoiQuanLy { get; set; }
        public string GhiChu { get; set; }
    
        public virtual NhanSu NhanSu { get; set; }
    }
}
